Raise ValueError for non-existent username
Also separate errors into different except blocks,
which makes for a more informative error message.

The format of raising the CommandError with e.args[0] after catching
ValidationError is due to DRF's interesting way of storing exceptions,
which get printed as:
```
CommandError: [ErrorDetail(string="Cannot make rubric of kind 'qwerty'.",
code='invalid')]
```